In [1]:
# lable encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

le.fit(items)
lables = le.transform(items)
print(lables)

[0 1 4 5 3 3 2 2]


In [6]:
# one-hot encoding
import numpy as np
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()
items = np.array(items).reshape(-1, 1)
ohe.fit(items)
labels = ohe.transform(items)

print(labels)
print(labels.toarray())

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 4)	1.0
  (3, 5)	1.0
  (4, 3)	1.0
  (5, 3)	1.0
  (6, 2)	1.0
  (7, 2)	1.0
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


pandas에서 제공하는 get_dummies 메소드를 이용하면 문자열 카테로기 값을 숫자형으로 변환할 필요없이 바로 변환이 가능하다.

In [8]:
import pandas as pd

df = pd.DataFrame({'item':['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})
print(df)
pd.get_dummies(df)

    item
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서


item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

# 피처 스케일링
> 서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업
- 표준화
    - StandardScaler
- 정규화

이때 train에서 scaler를 이용해 test에 적용해야 한다

In [9]:
# 표준화
from sklearn.datasets import load_iris

iris = load_iris()
data = iris.data

iris_df = pd.DataFrame(data, columns=iris.feature_names)

In [10]:
print('평균: ', iris_df.mean())
print('분산: ', iris_df.var())

평균:  sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
분산:  sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(iris_df)
iris_scale = scaler.transform(iris_df)

iris_scale_df = pd.DataFrame(iris_scale, columns=iris.feature_names)
print('평균: ', iris_scale_df.mean())
print('분산: ', iris_scale_df.var())

평균:  sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
분산:  sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64
